name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Log node new version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Log node new version
        uses: docker://node:12.14.1-alpine3.10
        run: |
          node -v
          cat /etc/os-release